name: salescrm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  form_field_validator: ^1.1.0
  fluttertoast: ^8.2.8
  json_annotation: any
  horizontal_data_table: ^4.3.1
  pie_chart: ^5.1.0
  fl_chart: ^0.46.0
  #charts_flutter: ^0.12.0
  device_preview: ^1.0.0
  shared_preferences: ^2.0.13
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  flutter_tts: ^3.3.3
  translator: ^0.1.7
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
 # flutter_webview_plugin: ^0.4.0
  readmore: ^2.1.0
  image_picker: ^0.8.5+3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.3.2
  persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.4
  geolocator: ^9.0.0
  percent_indicator: ^4.2.2
  gainer_crypto: ^0.0.6
  dio: ^4.0.6
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_downloader: ^1.8.3
  permission_handler: ^10.0.0
  external_path: ^2.0.1
  flutter_switch: ^0.3.2
  google_sign_in: ^5.4.2
  tflite_flutter: ^0.10.1
  #splashscreen: ^1.3.5


dev_dependencies:
  json_serializable: any
  build_runner: any
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "image/saleslogo.png"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - image/
    - files/
    - assets/maptheme/dark_theme.json

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
