class Autogenerated {
  String? status;
  List<DutyDetailsAlertsDetail>? dutyDetails;

  Autogenerated({this.status, this.dutyDetails});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['dutyDetails'] != null) {
      dutyDetails = <DutyDetailsAlertsDetail>[];
      json['dutyDetails'].forEach((v) {
        dutyDetails!.add(new DutyDetailsAlertsDetail.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.dutyDetails != null) {
      data['dutyDetails'] = this.dutyDetails!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DutyDetailsAlertsDetail {
  String? id;
  String? tourName;
  String? tourId;
  String? pickupTime;
  String? dropTime;
  String? startReading;
  String? endReading;
  String? actualPickupTime;
  String? actualdropTime;
  String? tourDate;

  DutyDetailsAlertsDetail(
      {this.id,
        this.tourName,
        this.tourId,
        this.pickupTime,
        this.dropTime,
        this.startReading,
        this.endReading,
        this.actualPickupTime,
        this.actualdropTime,
        this.tourDate});

  DutyDetailsAlertsDetail.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    tourName = json['tourName'];
    tourId = json['tourId'];
    pickupTime = json['pickupTime'];
    dropTime = json['dropTime'];
    startReading = json['startReading'];
    endReading = json['endReading'];
    actualPickupTime = json['actualPickupTime'];
    actualdropTime = json['actualdropTime'];
    tourDate = json['tourDate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['tourName'] = this.tourName;
    data['tourId'] = this.tourId;
    data['pickupTime'] = this.pickupTime;
    data['dropTime'] = this.dropTime;
    data['startReading'] = this.startReading;
    data['endReading'] = this.endReading;
    data['actualPickupTime'] = this.actualPickupTime;
    data['actualdropTime'] = this.actualdropTime;
    data['tourDate'] = this.tourDate;
    return data;
  }
}
