name: driverapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  fluttertoast: ^8.0.9
  json_annotation: any
  horizontal_data_table: ^3.6.1+1
  pie_chart: ^5.1.0
 # fl_chart: ^0.46.0
  #charts_flutter: ^0.12.0
  device_preview: ^1.0.0
  shared_preferences: ^2.0.13
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  flutter_tts: ^3.3.3
  translator: ^0.1.7
  pin_code_fields: ^8.0.1
  webview_flutter: ^3.0.4
 #  flutter_webview_plugin: ^0.4.0
  readmore: ^2.1.0
  #image_picker: ^0.8.5+3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.3.2
  path_provider: ^2.0.10
  #persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.4
  geolocator: ^9.0.0
  flutter_switch: ^0.3.2

dev_dependencies:
  json_serializable: any
  build_runner: any
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "image/guideappicon.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - image/

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 400

    # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
