class Autogenerated {
  bool? status;
  List<ArticlesBussinessType>? articles;

  Autogenerated({this.status, this.articles});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['articles'] != null) {
      articles = <ArticlesBussinessType>[];
      json['articles'].forEach((v) {
        articles!.add(new ArticlesBussinessType.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.articles != null) {
      data['articles'] = this.articles!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ArticlesBussinessType {
  String? id;
  String? name;

  ArticlesBussinessType({this.id, this.name});

  ArticlesBussinessType.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}


